### PR TITLE
Attempt to fix vertical padding on pixel coordinate div in imviz

### PR DESCRIPTION
**Pull request by kecnry**
### Description

The font that is rendered by notebook vs lab seem to be slightly different, so centering with a fixed padding is inconsistent. 
 This pull request attempts to give more consistent padding to the pixel display in imviz by vertically centering the div and providing a fixed line height.  

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by pllim — COMMENTED** [review]
The padding is fixed but "Pixel" row now jumps to the center when WCS is not present.

What do you think, @jenneh ?

### Without this patch

Screenshot 2021-11-24 012714

Screenshot 2021-11-24 012038

Screenshot 2021-11-24 011948


### With this patch

Screenshot 2021-11-30 123724

Screenshot 2021-11-30 123857

Screenshot 2021-11-30 123934

**Comment by kecnry** [comment]
Yes, that's true, it will always vertically center the contents.  If we don't want that, we can add empty placeholders with a fixed height for the other "rows" so that the pixel row is always near the top.

**Comment by pllim** [comment]
I don't have a preference but maybe @patrickogle or @jenneh does.

**Comment by rosteen** [comment]
See https://vuetifyjs.com/en/components/grids/ for vuetify alignment stuff, specifically https://vuetifyjs.com/en/components/grids/#align.

**Comment by rosteen** [comment]
You may need to put a `<v-container>` inside the `div` to take advantage of the vuetify features.

**Comment by pllim** [comment]
I can't get VueJS to work. I tried adding a `<v-container>` `<v-row align="start">` `<v-col>` layer outside of `<div>` and I get something horrible. I found a non-VueJS workaround though.

Screenshot 2021-12-01 144200

**Comment by pllim** [comment]
Thanks, everyone!

**Comment by Jenneh** [comment]
It is nice that it always vertically centers. Padding looks better. It is still a little uncomfortably close to the edges but I think this is good enough for now.

**Pull request merged**
