### PR TITLE
Enable updates to contrast/bias on dragging

### PR DESCRIPTION
**Pull request by astrofrog**
For https://github.com/spacetelescope/jdaviz/pull/553

### CODE REVIEW

**Comment by astrofrog** [comment]
So this works... sometimes but not others! Still investigating, but feel free to merge if it works for you.

**Comment by astrofrog** [comment]
Ah ok so I think I've tracked it down to an issue in bqtplot-image-gl, will update soon

**Comment by astrofrog** [comment]
Ok so issues are documented here: https://github.com/glue-viz/bqplot-image-gl/issues/52 - please don't merge this yet.

**Comment by pllim** [comment]
Gotcha. I converted it to draft. You can remove draft status when we can merge. Thanks!

**Comment by pllim** [comment]
Sorry, I force pushed on my PR and now the diff looks weird. You might have to rebase.

**Comment by astrofrog** [comment]
This now works with the latest developer version of bqplot-image-gl, and we'll do a release of it soon

**Comment by pllim** [comment]
I will review soon, I promise!

**Review by pllim — APPROVED** [review]
Works beautifully with dev version of `bqplot-image-gl`. Much better than just clicking around. Thanks!

**Pull request merged**
